{{- if .Values.storage.minikube.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default
annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
parameters:
  type: default
reclaimPolicy: Retain
mountOptions:
  - debug
allowVolumeExpansion: true
{{- end }}