{{- if .Values.elasticsearch.deployment.enabled -}}
# Elasticsearch service: API
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-elasticsearch-api
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: Elasticsearch-svc
    app: {{ include "wazuh.fullname" .}}-elasticsearch
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: Elasticsearch-svc
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
{{ include "labels" $ | indent 4 }}
    app: {{ include "wazuh.fullname" .}}-elasticsearch
  ports:
    - name: es-rest
      port: {{ .Values.elasticsearch.service.httpPort }}
      targetPort: 9200
{{- end -}}