{{-if .Values.elasticsearch.deployment.enabled -}}
# Elasticsearch service: API
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: wazuh
  labels:
    app: wazuh-elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
    app: wazuh-elasticsearch
  ports:
    - name: es-rest
      port: {{ .Values.elasticsearch.service.httpPort }}
      targetPort: 9200
{{- end -}}