{{-if .Values.kibana.deployment.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: wazuh
  labels:
    app: wazuh-kibana
{{-if .Values.aws.elb.dns53.enabled-}}
    dns: route53
{{- end -}}
  annotations:
{{-if .Values.aws.elb.enabled and if .Values.aws.kibana.enabled }}
{{-if .Values.aws.elb.dns53.enabled -}}
    domainName: {{ .Values.aws.elb.dns53.wazuhMasterDomain | quote }}
{{- end -}}
{{- if .Values.aws.elb.cert.enabled -}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.aws.elb.cert.certName | quote }}
{{- end -}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: {{ .Values.aws.elb.kibana.port | quote }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.aws.elb.kibana.backEnd | quote}}
{{- end -}}
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: {{ .Values.kibana.service.httpPort }}
      targetPort: 5601
{{- end -}}