{{- if .Values.kibana.deployment.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-kibana
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: Kibana-svc
    app: {{ include "appIdentifier" .Values.identifier  }}-kibana
{{ include "route53.dns.labels" $ | indent 4 }}
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: kibana-svc
{{ include "aws.annotations" $ | indent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: {{ .Values.kibana.service.httpPort }}
      targetPort: 5601
{{- end -}}