{{-if .Values.kibana.deployment.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: wazuh
  labels:
    app: wazuh-kibana
    # dns: route53
  annotations:
{{-if .Values.aws.elb.enabled and if .Values.aws.kibana.enabled }}
{{-if .Values.aws.ELB_CERT.enabled }}
    # domainName: 'changeme'
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'changeme'
{{- end -}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '{{ .Values.kibana.service.awsLbSslPort }}'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.kibana.awsLbBackEnd }}
{{- end -}}
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: {{ .Values.kibana.service.httpPort }}
      targetPort: 5601
{{- end -}}