{{-if .Values.wazuh.deployment.enabled -}}
# Wazuh workers service: Agent reporting
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
{{-if .Values.aws.elb.dns53.enabled -}}
    dns: route53
{{- end -}}
  annotations:
  {{-if .Values.aws.elb.enabled. and if .Values.aws.wazuh_worker.enabled -}}
  {{-if .Values.aws.elb.dns53.enabled -}}
    domainName: {{ .Values.aws.dns53.wazuhWorkerDomain | quote }}
  {{- end -}}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.aws.elb.protocol }}
  {{- end -}}
spec:
  type: {{ .Values.wazuh.service.workerType }}
  selector:
    app: wazuh-manager
    node-type: {{ .Values.wazuh.service.w_nodeType }}
  ports:
    - name: agents-events
      port: {{ .Values.wazuh.service.ports.agentEvents }}
      targetPort: 1514
{{- end -}}