{{- if .Values.wazuh.deployment.enabled -}}
# Wazuh master Service: API and registration (authd)
apiVersion: v1
kind: Service
metadata:
  name: wazuh-master
  labels:
    app: wazuh-manager
{{ include "route53.dns.labels" $ | indent 4 }}
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: wazuh-manager
{{ include "aws.annotations" $ | indent 4 }}
spec:
  type: {{ .Values.wazuh.service.type }}
  selector:
    app: wazuh-manager
    node-type: {{ .Values.wazuh.service.masterType }}
  ports:
    - name: registration
      port: {{ .Values.wazuh.service.ports.registration }}
      targetPort: 1515
    - name: api
      port: {{ .Values.wazuh.service.ports.api }}
      targetPort: 55000
{{- end -}}