{{- if .Values.wazuh.deployment.enabled }}
# Wazuh workers service: Agent reporting
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  labels:
    app: wazuh-manager
{{ include "route53.dns.labels" $ | indent 4 }}
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: wazuh-manager
{{ include "aws.annotations" $ | indent 4 }}
spec:
  type: {{ .Values.wazuh.service.workerType }}
  selector:
    app: wazuh-manager
    node-type: {{ .Values.wazuh.service.w_nodeType }}
  ports:
    - name: agents-events
      port: {{ .Values.wazuh.service.ports.agentEvents }}
      targetPort: 1514
{{- end -}}