{{- if .Values.wazuh.deployment.enabled -}}
# Wazuh cluster Service: Manager nodes communication
apiVersion: v1
kind: Service
metadata:
  name: wazuh-cluster
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
  ports:
    - name: cluster
      port: {{ .Values.wazuh.service.ports.wazuhInternal }}
      targetPort: 1516
  clusterIP: None
{{- end -}}