{{- if .Values.agent.deployment.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}-agent-daemonset
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: Wazuh-Agent-DaemonSet
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: Wazuh-Agent-DaemonSet
spec:
  selector:
    matchLabels:
      name: {{ include "appIdentifier" .Values.identifier }}-agent-daemonset
      labels:
{{ include "labels" $ | indent 8 }}
        appComponent: Wazuh-Agent-DaemonSet
      annotations:
{{ include "annotations" $ | indent 8 }}
        appComponent: Wazuh-Agent-DaemonSet
  template:
    metadata:
      labels:
        name: {{ include "appIdentifier" .Values.identifier }}-agent-daemonset
{{ include "labels" $ | indent 8 }}
        appComponent: Wazuh-Agent-DaemonSet
      annotations:
{{ include "annotations" $ | indent 8 }}
        appComponent: Wazuh-Agent-DaemonSet
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
{{- if .Values.agent.image.imagePullSecrets.enabled -}}
      imagePullSecrets:
        - name: {{ .Values.agent.image.imagePullSecrets.name | quote }}
{{- end -}}
      containers:
        - name: wazuh-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: W_MANAGER
              value: {{ .Values.agent.env.W_MANAGER | quote }}
          resources:
{{toYaml .Values.agent.image.resources | indent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: ossec-conf
              mountPath: /var/ossec/etc/ossec.conf
              subPath: ossec.conf
            - name: wazuh-authd-pass
              mountPath: /var/ossec/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      terminationGracePeriodSeconds: 1
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: ossec-conf
          configMap:
            name: ossec-conf
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      serviceAccount: wazuh-agent
      serviceAccountName: wazuh-agent
{{- end -}}