{{- if .Values.kibana.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wazuh.kibana.fullname" . }}-dpl
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: Kibana-Deployment
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: Kibana-Deployment
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
{{ include "labels" $ | indent 6 }}
    role: kibana
  serviceName: {{ include "appIdentifier" .Values.identifier }}-kibana-svc
  template:
    metadata:
      labels:
{{ include "labels" $ | indent 8 }}
        appComponent: Kibana-Pod
        app: {{ include "appIdentifier" .Values.identifier }}-kibana-dpl
      annotations:
        appComponent: Kibana-Pod
      name: {{ include "appIdentifier" .Values.identifier }}-kibana-dpl
    spec:
      volumes:
        - name: kibana-certs
          secret:
            secretName: kibana-certs
      containers:
        - name: odfe-kibana-w-wazuh
          image: "{{ .Values.kibana.images.repository }}:{{ .Values.kibana.images.tag }}"
          resources:
{{ toYaml .Values.kibana.images.resources | indent 12 }}
          volumeMounts:
            - name: kibana-certs
              mountPath: /usr/share/kibana/config/cert.pem
              readOnly: true
              subPath: cert.pem
            - name: kibana-certs
              mountPath: /usr/share/kibana/config/key.pem
              readOnly: true
              subPath: key.pem
          ports:
            - containerPort: {{ .Values.kibana.service.httpPort }}
              name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: {{ .Values.kibana.env.ELASTICSEARCH_URL | quote }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: password
            - name: SERVER_SSL_ENABLED
              value: {{ .Values.kibana.enable_ssl | quote }}
            - name: SERVER_SSL_CERTIFICATE
              value: /usr/share/kibana/config/cert.pem
            - name: SERVER_SSL_KEY
              value: /usr/share/kibana/config/key.pem
            - name: WAZUH_API_URL
              value: {{ .Values.kibana.env.WAZUH_API_URL | quote }}
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
{{- end -}}