#AWS load balancer enabled for using ELB(AWS Elastic Load Balancer)
#Some resources require loadbalancer. Refer to Wazuh documentation for more information
aws:

  elb:
    enabled: true
    protocol: tcp
    
    # Enabled custom certificates for AWS ELB
    cert:
      enabled: false
      certName: demoCert

    # Enabled AWS ELB for Kibana Service
    kibana:
      enabled: false
      port: 443
      backEnd: https

    # AWS ELB for Elasticsearch Service
    elasticsearch:
      enabled: false

    # AWS ELB for Wazuh Master Service
    wazuh_master:
      enabled: true

    # AWS LB for Wazuh worker Service
    wazuh_worker:
      enabled: true
    
    dns53:
      enabled: false
      wazuhMasterDomain: foobar.com
      
# Elasticsearch statefulset deployment
elasticsearch:
  
  deployment:
    enabled: true
    
  selfcert:
    enabled: false
    
  elkversion: "7.9.1"
  
  elasticsearch:
    discoveryOverride: ""

  service:
    httpPort: 9200
    transport: 9300
    metrics: 9600
    type: ClusterIP
    
  images: 
    repository: amazon/opendistro-for-elasticsearch
    tag: "1.11.0"
    pullPolicy: IfNotPresent
    updateStrategy: RollingUpdate
    # If you're using private registry add secret name for docker credentials
    pullSecret: {}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 800m
        memory: 2Gi
  
  config:
  
  env:
    CLUSTER_NAME: "wazuh"
    #NETWORK_HOST: "_eth0_"
    NETWORK_HOST: "0.0.0.0"
    HTTP_CORS_ENABLE: "false"
    ALLOW_DEMOCERTIFICATES: "false"
    # The minimum number of masters that will be able to form a quorum. This
    # should be (#masters / 2) + 1. Default is 2.
    NUMBER_OF_MASTERS: "3"
    DISCOVERY_SERVICE: "wazuh-elasticsearch"
    
  plugins: []
  
  # Default users provided by Wazuh
  # Check wazuh documentation for default credentials
  internal_users:
    admin: "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO"
    kibanaserver: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
    kibanaro: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
    logstash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2"
    readall: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
    snapshotrestore: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"

    storageSize: 50Gi
    storageClassName: default

# Kibana for elasticsearch with Wazuh plugins pre-installed
kibana:

  deployment:
    enabled: true

  images:
    repository: wazuh/wazuh-kibana-odfe
    tag: "4.0.4_1.11.0"
    pullPolicy: IfNotPresent
    updateStrategy: OnDelete
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 900m
        memory: 1Gi
  # with this you will be able to access kibana on http port instead of https
  # if you use Ambassador edgestack this is necessary becasue 
  # with `true` route will close unexpectedly
  # when accessing via ambassador external url
  enable_ssl: false

  service:
    httpPort: 5601
    type: ClusterIP

  env:
    ELASTICSEARCH_URL: https://wazuh-elasticsearch-0.wazuh-elasticsearch:9200
    WAZUH_API_URL: https://wazuh-manager-master-0.wazuh-cluster
    
wazuh:

  deployment:
    enabled: true

  master_replicas: 1
  worker_replicas: 2
  
  images:
    repository: wazuh/wazuh-odfe
    tag: "4.0.4_1.11.0"
    pullSecret: regcred
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 850m
        memory: 1Gi
    worker_resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1500m
        memory: 2Gi
  
  
  env:
    FILEBEAT_SSL_VERIFICATION_MODE: none

  service:
    type: ClusterIP
    masterType: LoadBalancer
    workerType: LoadBalancer
    nodeType: master
    ports:
      registration: 1515
      api: 55000
      wazuhInternal: 1516
      agentEvents: 1514
      