{{- if .Values.agent.deployment.enabled }}
{{- if .Values.agent.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "appIdentifier" .Values.identifier }}
  labels:
{{ include "labels" $ | indent 4 }}
    appComponent: ClusterRole
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: ClusterRole
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
{{- end -}}
{{- end -}}